image: "gableroux/unity3d:2018.3.0f2-windows"

stages:
- test
- build
- deploy

variables:
  BUILD_NAME: Bulletfire

.unity_before_script: &unity_before_script
  before_script:
  - chmod +x ./ci/before_script.sh && ./ci/before_script.sh

#.test: &test
#  stage: test
#  <<: *unity_before_script
#  script:
#  - chmod +x ./ci/test.sh && ./ci/test.sh
#  artifacts:
#    paths:
#    - $(pwd)/$TEST_PLATFORM-results.xml

#test-editmode:
#  <<: *test
#  variables:
#    TEST_PLATFORM: editmode

#test-playmode:
#  <<: *test
#  variables:
#    TEST_PLATFORM: playmode

.build: &build
  stage: build
  <<: *unity_before_script
  script:
  - chmod +x ./ci/build.sh && ./ci/build.sh

  artifacts:
    paths:
    - ./Builds/

#build-StandaloneLinux64:
#  <<: *build
#  variables:
#    BUILD_TARGET: StandaloneLinux64

#build-StandaloneOSX:
#  <<: *build
#  variables:
#    BUILD_TARGET: StandaloneOSX

build-StandaloneWindows64:
  <<: *build
  variables:
    BUILD_TARGET: StandaloneWindows64

